### ISSUE TITLE
CocoaPods Error On Build

### ISSUE THREAD

**Issue by epmatsw** [thoughtbot/Tropos#128]
I'm trying to build the app on my laptop, but I'm running into an issue with bin/setup.

It looks like the gemfile installs 0.35.0, but the pods file actually requires 0.37+. Running `bundle update` followed by `./bin/setup` appears to fix the error. This is using ruby 2.2.1p85 on OSX 10.11.

```
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Installing i18n 0.6.11
Using json 1.8.1
Installing minitest 5.4.3
Installing thread_safe 0.3.4
Installing tzinfo 1.2.2
Installing activesupport 4.1.8
Installing claide 0.7.0
Installing fuzzy_match 2.0.4
Installing nap 0.8.0
Installing cocoapods-core 0.35.0
Installing cocoapods-downloader 0.8.0
Installing cocoapods-plugins 0.3.2
Installing netrc 0.7.8
Installing cocoapods-trunk 0.4.1
Installing cocoapods-try 0.4.2
Using colored 1.2
Installing escape 0.0.4
Installing molinillo 0.1.2
Installing open4 1.3.4
Installing xcodeproj 0.20.2
Installing cocoapods 0.35.0
Installing xcpretty 0.1.7
Using bundler 1.10.4
Bundle complete! 2 Gemfile dependencies, 23 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Analyzing dependencies
[!] The version of CocoaPods used to generate the lockfile (0.37.2) is higher than the version of the current executable (0.35.0). Incompatibility issues may arise.
/Users/will/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/pathname.rb:430:in `open': No such file or directory @ dir_initialize - /Users/will/.cocoapods/repos (Errno::ENOENT)
	from /Users/will/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/pathname.rb:430:in `foreach'
	from /Users/will/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/pathname.rb:430:in `children'
	from /Users/will/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.35.0/lib/cocoapods/sources_manager.rb:63:in `all'
	from /Users/will/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.35.0/lib/cocoapods/user_interface/error_report.rb:130:in `repo_information'
	from /Users/will/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.35.0/lib/cocoapods/user_interface/error_report.rb:34:in `report'
	from /Users/will/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.35.0/lib/cocoapods/command.rb:58:in `report_error'
	from /Users/will/.rvm/gems/ruby-2.2.1/gems/claide-0.7.0/lib/claide/command.rb:300:in `handle_exception'
	from /Users/will/.rvm/gems/ruby-2.2.1/gems/claide-0.7.0/lib/claide/command.rb:274:in `rescue in run'
	from /Users/will/.rvm/gems/ruby-2.2.1/gems/claide-0.7.0/lib/claide/command.rb:264:in `run'
	from /Users/will/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.35.0/lib/cocoapods/command.rb:45:in `run'
	from /Users/will/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.35.0/bin/pod:43:in `<top (required)>'
	from /Users/will/.rvm/gems/ruby-2.2.1/bin/pod:23:in `load'
	from /Users/will/.rvm/gems/ruby-2.2.1/bin/pod:23:in `<main>'
	from /Users/will/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/will/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'

-------------------------------------------------
Created Tropos/Secrets.h. Please add your keys to it.
-------------------------------------------------
```

**Comment by jakecraige** [comment]
Thanks for reporting this. Would you be interested in opening a PR to fix this?

**Comment by jakecraige** [comment]
Closing in favor of #129
